### PR TITLE
Devices stats

### PR DESCRIPTION
**Pull request by Meisterschueler**

### CODE REVIEW

**Comment by kerel-fs** [comment]
This change breaks the follwing command:
```
./manage.py db.update_ddb_ogn
```
Traceback:
```
  File "/home/birke/Fliegen/ogn/ogn-python/ogn/commands/database.py", line 23, in update_ddb_ogn
    counter = result.get()
  File "/home/birke/Fliegen/ogn/ogn-python/env/lib/python3.4/site-packages/celery/result.py", line 175, in get
    raise meta['result']
sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Error binding parameter 0 - probably unsupported type. [SQL: 'DELETE FROM device WHERE device.address_origin = ?'] [parameters: (<AddressOrigin.ogn_ddb: 1>,)]
```

**Comment by kerel-fs** [comment]
@Meisterschueler 
We have to fix this line at least:
https://github.com/glidernet/ogn-python/blob/master/ogn/collect/fetchddb.py#L17

...and all other occurrences of AddressOrigin.

**Comment by Meisterschueler** [comment]
Strage... obviously it has something to do with the Enum. But on my side everything is running (python3.5, sqlite/postgresql)

**Comment by kerel-fs** [comment]
I like your idea to change AddressOrigin to an enumeration, but using an IntEnum annihilates its advantages as it is possible to access the (arbitrary) integer values.

**Pull request closed without merging**
