### PR TITLE
Update receiver table

### PR DESCRIPTION
**Pull request by Meisterschueler**
Created a new task for population and updating receiver table.

### CODE REVIEW

**Comment by kerel-fs** [comment]
Does work with postgresql backend, breaks with sqlite backend.
Execution time: 82s for 8000 Receiver Beacons (receiver table empty).

**Comment by kerel-fs** [comment]
```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "FROM": syntax error [SQL: 'UPDATE receiver SET latitude=anon_1.latitude, longitude=anon_1.longitude, country_code=? FROM (SELECT receiver_beacon.name AS name, receiver_beacon.latitude AS latitude, receiver_beacon.longitude AS longitude, receiver_beacon.altitude AS altitude, anon_2.firstseen AS firstseen, anon_2.lastseen AS lastseen, receiver_beacon.version AS version, receiver_beacon.platform AS platform \nFROM receiver_beacon, (SELECT receiver_beacon.name AS name, min(receiver_beacon.timestamp) AS firstseen, max(receiver_beacon.timestamp) AS lastseen \nFROM receiver_beacon, (SELECT coalesce(max(receiver.lastseen), ?) AS last_entry \nFROM receiver) AS anon_3 \nWHERE receiver_beacon.timestamp >= anon_3.last_entry GROUP BY receiver_beacon.name) AS anon_2 \nWHERE receiver_beacon.name = anon_2.name AND receiver_beacon.timestamp = anon_2.lastseen) AS anon_1 WHERE receiver.name = anon_1.name AND (receiver.latitude != anon_1.latitude OR receiver.longitude != anon_1.longitude)'] [parameters: (None, '2015-01-01 00:00:00')]
```

**Comment by Meisterschueler** [comment]
Execution time is okay, because for every new receiver (or receiver with changed lat/lon) a http request is executed to get the 'country_code'.

**Comment by kerel-fs** [comment]
Yes, it's ok (especially since this code is not part of the core functionality of ogn-python). Just wanted to show my test result.

Do you have any idea about the sqlite-backend issue? If not, I will add a note in the README (the same for the logbook-feature). Anyway we should recommend the sqlite backend only for testing.

**Comment by Meisterschueler** [comment]
No idea with sqlite... I think a note concerning sqlite would be good

**Pull request merged**
